import json
import logging
import time
import urllib.request
import urllib.error
from config import GEMINI_API_KEY, GEMINI_MODEL, SYSTEM_PROMPTS, ROUTER_SYSTEM_PROMPT

logger = logging.getLogger(__name__)

# Fallback models in priority order for resilience against temporary high-demand (503) spikes
CANDIDATE_MODELS = list(dict.fromkeys([
    GEMINI_MODEL,
    "gemini-3.7-flash",
    "gemini-3.5-flash",
    "gemini-3.1-flash-lite",
    "gemini-flash-latest"
]))

def call_gemini(prompt: str, skill_key: str = None, user_context: str = None) -> str:
    """
    Calls Gemini API with the specialized skill prompt as system instruction.
    Includes automatic retries with exponential backoff for transient 503/429 errors
    and graceful fallback across model tiers.
    """
    if not GEMINI_API_KEY:
        return "⚠️ Error: GEMINI_API_KEY is not configured in .env file."

    # Select system prompt
    system_instruction = SYSTEM_PROMPTS.get(skill_key, ROUTER_SYSTEM_PROMPT)
    if not system_instruction:
        system_instruction = ROUTER_SYSTEM_PROMPT

    # Compose full user message
    full_prompt = prompt
    if user_context:
        full_prompt = f"User Profile / Context:\n{user_context}\n\nQuery:\n{prompt}"

    payload = {
        "contents": [
            {
                "role": "user",
                "parts": [{"text": full_prompt}]
            }
        ],
        "systemInstruction": {
            "role": "system",
            "parts": [{"text": system_instruction}]
        },
        "generationConfig": {
            "temperature": 0.3,
            "maxOutputTokens": 16384,
            "thinkingConfig": {
                "thinkingBudget": 1024
            }
        }
    }

    req_data = json.dumps(payload).encode("utf-8")
    last_error = None

    for model_name in CANDIDATE_MODELS:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent?key={GEMINI_API_KEY}"
        req = urllib.request.Request(
            url,
            data=req_data,
            headers={"Content-Type": "application/json"}
        )

        max_retries = 3
        backoff_delays = [2, 4, 8]

        for attempt in range(max_retries):
            try:
                logger.info(f"Calling Gemini API (model: {model_name}, attempt: {attempt + 1})...")
                with urllib.request.urlopen(req, timeout=120) as response:
                    res_data = json.loads(response.read().decode("utf-8"))
                    candidates = res_data.get("candidates", [])
                    if candidates:
                        cand = candidates[0]
                        if cand.get("finishReason") == "MAX_TOKENS":
                            logger.warning(f"Gemini response reached MAX_TOKENS limit on {model_name}.")
                        parts = cand.get("content", {}).get("parts", [])
                        text_parts = [part.get("text", "") for part in parts if not part.get("thought", False)]
                        return "".join(text_parts)
                    return "No response generated by Gemini."
            except urllib.error.HTTPError as e:
                err_body = e.read().decode("utf-8", errors="replace")
                last_error = f"HTTP {e.code}: {err_body}"
                # 503 = Service Unavailable (high demand spike), 429 = Rate limit
                if e.code in (503, 429) and attempt < max_retries - 1:
                    sleep_time = backoff_delays[attempt]
                    logger.warning(f"Model {model_name} returned {e.code} (high demand). Retrying in {sleep_time}s...")
                    time.sleep(sleep_time)
                    continue
                else:
                    logger.warning(f"Model {model_name} returned {e.code}: {err_body}. Trying next model tier if available.")
                    break
            except Exception as e:
                last_error = str(e)
                if attempt < max_retries - 1:
                    sleep_time = backoff_delays[attempt]
                    logger.warning(f"Connection error with {model_name}: {e}. Retrying in {sleep_time}s...")
                    time.sleep(sleep_time)
                    continue
                break

    # If all candidate models and retries were exhausted
    logger.error(f"All Gemini models exhausted. Last error: {last_error}")
    return (
        "⚠️ **Google Gemini Server Temporary High Demand (503)**\n\n"
        "Google's AI servers are temporarily experiencing high traffic spikes. "
        "The application automatically attempted retries and model fallbacks.\n\n"
        "👉 **Please wait a few seconds and click the submit button again.**"
    )
